# Site Info
title: manong
tagline: "blog"
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://manong-x.github.io" target="_blank">@manong-x</a>.'
baseurl: ""
url: https://manong-x.github.io/
logo: "/public/logo.png"

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: "/blog/page:num"
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: manong
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    github: https://github.com/manong-x
    email: dmltkd1003@gmail.com
    # linkedin:  https://www.linkedin.com/in/404
    # facebook:  <hide>
    # twitter:   https://twitter.com/404

# Navigation (2nd level links supported)
nav:
  Home:
    - "/"
  Blog:
    - "/blog/"
    - { Categories: "/blog/categories/" }
    - { Tags: "/blog/tags/" }
  About:
    - "/about/"
  # Github Project:
  # - 'http://manong-x.github.io/'

# Where are tags and categories displayed
tag_page: "/blog/tags/"
category_page: "/blog/categories/"

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
# google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
google_analytics_token: "UA-137374202-1" # leave blank if you don't want google analytics
disqus_short_name: "manong-blog" # leave blank if you don't want disqus

